# Generated by Django 5.2.4 on 2025-07-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0002_prayersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayeractivity',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='prayeractivity',
            name='lng',
            field=models.FloatField(null=True),
        ),
    ]
