# Generated by Django 5.2.4 on 2025-07-21 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0003_prayeractivity_lat_prayeractivity_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysterySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('days', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mystery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('scripture_reference', models.CharField(blank=True, max_length=100)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mysteries', to='rosary.mysteryset')),
            ],
        ),
        migrations.CreateModel(
            name='DecadeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('repeat', models.PositiveIntegerField(default=1)),
                ('mystery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='rosary.mystery')),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rosary.prayer')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
