# Generated by Django 5.2.4 on 2025-07-21 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosary', '0004_mysteryset_prayer_mystery_decadestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerSequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('repeat', models.PositiveIntegerField(default=1)),
                ('prayer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rosary.prayer')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='rosary.prayersequence')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
